#!/bin/sh

`dirname $0`/erl_tool_start generate_all_record $@ 
. `dirname $0`/tools_env
${ERL_DIR}erlc +debug_info -o  $SERVER_HOME/ebin/ -I$SERVER_HOME/include -I$SERVER_HOME/deps $SERVER_HOME/src/tools/all_record.erl
