#!/bin/sh

. `dirname $0`/tools_env
[ -f `dirname $0`/custom_tools_env ] && . `dirname $0`/custom_tools_env

${ERL_DIR}erl \
    -pa $SERVER_EBIN_ROOT \
    -args_file $VMARGS_PATH \
    -name tool@127.0.0.1 \
    -boot start_clean \
    -s make_record \
    -noshell \
    -extra "$@"
